const qs = {
    r02m12: [
        ''
        , 'https://www.fe-siken.com/kakomon/17_haru/q1.html'
        , 'https://www.fe-siken.com/kakomon/02_menjo/q2.html'
        , 'https://www.fe-siken.com/kakomon/17_haru/q9.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q6.html'
        , 'https://www.fe-siken.com/kakomon/23_toku/q3.html'
        , 'https://www.fe-siken.com/kakomon/25_haru/q4.html'
        , 'https://www.fe-siken.com/kakomon/27_haru/q5.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q9.html'
        , 'https://www.fe-siken.com/kakomon/19_aki/q15.html'
        , 'https://www.fe-siken.com/kakomon/29_haru/q7.html'
        , 'https://www.fe-siken.com/kakomon/28_haru/q10.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q13.html'
        , 'https://www.fe-siken.com/kakomon/26_haru/q10.html'
        , 'https://www.fe-siken.com/kakomon/29_haru/q11.html'
        , 'https://www.fe-siken.com/kakomon/01_moshi/q15.html'
        , 'https://www.fe-siken.com/kakomon/27_aki/q14.html'
        , 'https://www.fe-siken.com/kakomon/29_haru/q16.html'
        , 'https://www.fe-siken.com/kakomon/29_haru/q17.html'
        , 'https://www.fe-siken.com/kakomon/26_aki/q19.html'
        , 'https://www.fe-siken.com/kakomon/25_haru/q23.html'
        , 'https://www.fe-siken.com/kakomon/30_haru/q21.html'
        , 'https://www.fe-siken.com/kakomon/02_menjo/q22.html'
        , 'https://www.fe-siken.com/kakomon/25_aki/q26.html'
        , 'https://www.fe-siken.com/kakomon/23_aki/q29.html'
        , 'https://www.fe-siken.com/kakomon/25_aki/q29.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q25.html'
        , 'https://www.fe-siken.com/kakomon/29_haru/q27.html'
        , 'https://www.fe-siken.com/kakomon/22_haru/q31.html'
        , 'https://www.fe-siken.com/kakomon/31_haru/q30.html'
        , 'https://www.fe-siken.com/kakomon/26_aki/q31.html'
        , 'https://www.fe-siken.com/kakomon/02_menjo/q31.html'
        , 'https://www.fe-siken.com/kakomon/24_aki/q35.html'
        , 'https://www.fe-siken.com/kakomon/23_aki/q39.html'
        , 'https://www.fe-siken.com/kakomon/24_haru/q37.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q35.html'
        , 'https://www.fe-siken.com/kakomon/29_aki/q40.html'
        , 'https://www.fe-siken.com/kakomon/30_haru/q37.html'
        , 'https://www.fe-siken.com/kakomon/27_aki/q37.html'
        , 'https://www.fe-siken.com/kakomon/30_haru/q38.html'
        , 'https://www.fe-siken.com/kakomon/26_aki/q40.html'
        , 'https://www.fe-siken.com/kakomon/30_haru/q42.html'
        , 'https://www.fe-siken.com/kakomon/26_haru/q44.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q44.html'
        , 'https://www.fe-siken.com/kakomon/28_haru/q36.html'
        , 'https://www.fe-siken.com/kakomon/28_aki/q46.html'
        , 'https://www.fe-siken.com/kakomon/26_aki/q46.html'
        , 'https://www.fe-siken.com/kakomon/20_aki/q44.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q48.html'
        , 'https://www.fe-siken.com/kakomon/22_aki/q49.html'
        , 'https://www.fe-siken.com/kakomon/21_haru/q49.html'
        , 'https://www.fe-siken.com/kakomon/02_menjo/q51.html'
        , 'https://www.fe-siken.com/kakomon/02_menjo/q53.html'
        , 'https://www.fe-siken.com/kakomon/27_aki/q53.html'
        , 'https://www.ap-siken.com/kakomon/25_haru/q53.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q56.html'
        , 'https://www.sg-siken.com/kakomon/30_aki/q40.html'
        , 'https://www.fe-siken.com/kakomon/02_menjo/q57.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q59.html'
        , 'https://www.fe-siken.com/kakomon/02_menjo/q59.html'
        , 'https://www.fe-siken.com/kakomon/28_aki/q60.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q62.html'
        , 'https://www.fe-siken.com/kakomon/01_moshi/q64.html'
        , 'https://www.fe-siken.com/kakomon/31_haru/q64.html'
        , 'https://www.fe-siken.com/kakomon/26_aki/q65.html'
        , 'https://www.fe-siken.com/kakomon/28_aki/q66.html'
        , 'https://www.fe-siken.com/kakomon/24_haru/q67.html'
        , 'https://www.fe-siken.com/kakomon/25_aki/q70.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q67.html'
        , 'https://www.fe-siken.com/kakomon/28_haru/q70.html'
        , 'https://www.fe-siken.com/kakomon/29_haru/q72.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q71.html'
        , 'https://www.fe-siken.com/kakomon/26_haru/q71.html'
        , 'https://www.fe-siken.com/kakomon/24_aki/q74.html'
        , 'https://www.fe-siken.com/kakomon/29_aki/q74.html'
        , 'https://www.fe-siken.com/kakomon/31_haru/q76.html'
        , 'https://www.fe-siken.com/kakomon/23_toku/q75.html'
        , 'https://www.fe-siken.com/kakomon/28_aki/q77.html'
        , 'https://www.fe-siken.com/kakomon/23_aki/q78.html'
        , 'https://www.fe-siken.com/kakomon/28_haru/q79.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q80.html'
    ]
    , r03m06: [
        ''
        , 'https://www.fe-siken.com/kakomon/26_haru/q1.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q4.html'
        , 'https://www.fe-siken.com/kakomon/19_haru/q6.html'
        , 'https://www.fe-siken.com/kakomon/26_haru/q4.html'
        , 'https://www.fe-siken.com/kakomon/30_haru/q4.html'
        , 'https://www.fe-siken.com/kakomon/28_haru/q3.html'
        , 'https://www.fe-siken.com/kakomon/22_aki/q5.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q8.html'
        , 'https://www.fe-siken.com/kakomon/23_toku/q6.html'
        , 'https://www.fe-siken.com/kakomon/25_haru/q8.html'
        , 'https://www.fe-siken.com/kakomon/22_aki/q9.html'
        , 'https://www.fe-siken.com/kakomon/23_toku/q10.html'
        , 'https://www.fe-siken.com/kakomon/28_aki/q11.html'
        , 'https://www.fe-siken.com/kakomon/27_aki/q11.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q15.html'
        , 'https://www.fe-siken.com/kakomon/28_aki/q15.html'
        , 'https://www.fe-siken.com/kakomon/19_aki/q27.html'
        , 'https://www.fe-siken.com/kakomon/16_aki/q30.html'
        , 'https://www.fe-siken.com/kakomon/23_aki/q22.html'
        , 'https://www.fe-siken.com/kakomon/24_aki/q22.html'
        , 'https://www.fe-siken.com/kakomon/29_aki/q22.html'
        , 'https://www.fe-siken.com/kakomon/26_aki/q23.html'
        , 'https://www.fe-siken.com/kakomon/29_haru/q23.html'
        , 'https://www.fe-siken.com/kakomon/25_aki/q27.html'
        , 'https://www.fe-siken.com/kakomon/31_haru/q28.html'
        , 'https://www.fe-siken.com/kakomon/26_haru/q29.html'
        , 'https://www.fe-siken.com/kakomon/21_haru/q35.html'
        , 'https://www.fe-siken.com/kakomon/26_aki/q30.html'
        , 'https://www.fe-siken.com/kakomon/22_haru/q33.html'
        , 'https://www.fe-siken.com/kakomon/24_haru/q34.html'
        , 'https://www.fe-siken.com/kakomon/24_haru/q35.html'
        , 'https://www.fe-siken.com/kakomon/26_aki/q34.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q33.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q34.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q35.html'
        , 'https://www.fe-siken.com/kakomon/25_aki/q38.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q38.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q38.html'
        , 'https://www.fe-siken.com/kakomon/25_haru/q43.html'
        , 'https://www.fe-siken.com/kakomon/28_haru/q41.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q42.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q41.html'
        , 'https://www.fe-siken.com/kakomon/27_aki/q45.html'
        , 'https://www.fe-siken.com/kakomon/31_haru/q44.html'
        , 'https://www.fe-siken.com/kakomon/18_aki/q40.html'
        , 'https://www.fe-siken.com/kakomon/23_toku/q49.html'
        , 'https://www.fe-siken.com/kakomon/24_haru/q47.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q49.html'
        , 'https://www.fe-siken.com/kakomon/26_aki/q50.html'
        , 'https://www.fe-siken.com/kakomon/25_haru/q50.html'
        , 'https://www.fe-siken.com/kakomon/25_aki/q52.html'
        , 'https://www.fe-siken.com/kakomon/16_aki/q54.html'
        , 'https://www.fe-siken.com/kakomon/19_aki/q49.html'
        , 'https://www.fe-siken.com/kakomon/30_haru/q53.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q55.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q55.html'
        , 'https://www.fe-siken.com/kakomon/23_aki/q56.html'
        , 'https://www.ap-siken.com/kakomon/30_haru/q58.html'
        , 'https://www.ap-siken.com/kakomon/01_aki/q59.html'
        , 'https://www.sc-siken.com/kakomon/21_haru/am2_25.html'
        , 'https://www.ap-siken.com/kakomon/26_aki/q61.html'
        , 'https://www.fe-siken.com/kakomon/22_haru/q61.html'
        , 'https://www.fe-siken.com/kakomon/31_haru/q62.html'
        , 'https://www.fe-siken.com/kakomon/30_haru/q64.html'
        , 'https://www.fe-siken.com/kakomon/26_aki/q67.html'
        , 'https://www.fe-siken.com/kakomon/27_haru/q67.html'
        , 'https://www.fe-siken.com/kakomon/23_aki/q68.html'
        , 'https://www.fe-siken.com/kakomon/29_haru/q68.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q69.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q70.html'
        , 'https://www.fe-siken.com/kakomon/24_aki/q73.html'
        , 'https://www.fe-siken.com/kakomon/28_aki/q72.html'
        , 'https://www.fe-siken.com/kakomon/29_haru/q73.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q73.html'
        , 'https://www.fe-siken.com/kakomon/21_aki/q75.html'
        , 'https://www.fe-siken.com/kakomon/23_toku/q73.html'
        , 'https://www.fe-siken.com/kakomon/24_aki/q76.html'
        , 'https://www.fe-siken.com/kakomon/29_haru/q78.html'
        , 'https://www.fe-siken.com/kakomon/24_haru/q78.html'
        , 'https://www.fe-siken.com/kakomon/27_aki/q79.html'
    ]
    , r03m07: [
        ''
        , 'https://www.fe-siken.com/kakomon/18_aki/q8.html'
        , 'https://www.fe-siken.com/kakomon/19_aki/q9.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q3.html'
        , 'https://www.fe-siken.com/kakomon/28_aki/q2.html'
        , 'https://www.fe-siken.com/kakomon/23_aki/q3.html'
        , 'https://www.fe-siken.com/kakomon/28_aki/q3.html'
        , 'https://www.fe-siken.com/kakomon/28_aki/q6.html'
        , 'https://www.fe-siken.com/kakomon/31_haru/q6.html'
        , 'https://www.fe-siken.com/kakomon/01_moshi/q5.html'
        , 'https://www.fe-siken.com/kakomon/20_aki/q14.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q9.html'
        , 'https://www.fe-siken.com/kakomon/30_haru/q10.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q12.html'
        , 'https://www.fe-siken.com/kakomon/28_aki/q12.html'
        , 'https://www.fe-siken.com/kakomon/27_haru/q13.html'
        , 'https://www.fe-siken.com/kakomon/21_haru/q16.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q17.html'
        , 'https://www.fe-siken.com/kakomon/25_aki/q17.html'
        , 'https://www.fe-siken.com/kakomon/18_haru/q37.html'
        , 'https://www.fe-siken.com/kakomon/28_aki/q21.html'
        , 'https://www.fe-siken.com/kakomon/30_haru/q22.html'
        , 'https://www.fe-siken.com/kakomon/27_aki/q23.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q23.html'
        , 'https://www.fe-siken.com/kakomon/24_haru/q26.html'
        , 'https://www.fe-siken.com/kakomon/26_aki/q26.html'
        , 'https://www.fe-siken.com/kakomon/26_aki/q27.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q27.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q29.html'
        , 'https://www.fe-siken.com/kakomon/29_haru/q29.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q30.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q31.html'
        , 'https://www.fe-siken.com/kakomon/23_aki/q37.html'
        , 'https://www.fe-siken.com/kakomon/22_aki/q36.html'
        , 'https://www.fe-siken.com/kakomon/19_haru/q52.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q36.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q36.html'
        , 'https://www.fe-siken.com/kakomon/29_haru/q38.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q38.html'
        , 'https://www.fe-siken.com/kakomon/26_haru/q43.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q40.html'
        , 'https://www.fe-siken.com/kakomon/24_aki/q41.html'
        , 'https://www.sg-siken.com/kakomon/31_haru/q15.html'
        , 'https://www.fe-siken.com/kakomon/27_aki/q43.html'
        , 'https://www.fe-siken.com/kakomon/26_aki/q45.html'
        , 'https://www.fe-siken.com/kakomon/24_aki/q47.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q48.html'
        , 'https://www.fe-siken.com/kakomon/26_haru/q48.html'
        , 'https://www.fe-siken.com/kakomon/23_aki/q48.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q50.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q50.html'
        , 'https://www.fe-siken.com/kakomon/22_aki/q51.html'
        , 'https://www.fe-siken.com/kakomon/24_aki/q52.html'
        , 'https://www.fe-siken.com/kakomon/30_haru/q54.html'
        , 'https://www.fe-siken.com/kakomon/20_aki/q46.html'
        , 'https://www.fe-siken.com/kakomon/31_haru/q56.html'
        , 'https://www.fe-siken.com/kakomon/20_haru/q49.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q57.html'
        , 'https://www.ap-siken.com/kakomon/31_haru/q58.html'
        , 'https://www.sg-siken.com/kakomon/30_aki/q39.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q60.html'
        , 'https://www.fe-siken.com/kakomon/28_aki/q62.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q62.html'
        , 'https://www.fe-siken.com/kakomon/26_haru/q63.html'
        , 'https://www.fe-siken.com/kakomon/24_aki/q64.html'
        , 'https://www.fe-siken.com/kakomon/21_haru/q64.html'
        , 'https://www.fe-siken.com/kakomon/25_aki/q68.html'
        , 'https://www.fe-siken.com/kakomon/25_aki/q69.html'
        , 'https://www.fe-siken.com/kakomon/26_aki/q70.html'
        , 'https://www.fe-siken.com/kakomon/30_haru/q69.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q71.html'
        , 'https://www.fe-siken.com/kakomon/29_aki/q72.html'
        , 'https://www.fe-siken.com/kakomon/24_haru/q73.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q73.html'
        , 'https://www.fe-siken.com/kakomon/31_haru/q73.html'
        , 'https://www.fe-siken.com/kakomon/28_aki/q76.html'
        , 'https://www.fe-siken.com/kakomon/22_aki/q77.html'
        , 'https://www.fe-siken.com/kakomon/28_aki/q78.html'
        , 'https://www.fe-siken.com/kakomon/25_aki/q77.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q78.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q80.html'
    ]
    , r03m12: [
        ''
        , 'https://www.fe-siken.com/kakomon/03_menjo/q1.html'
        , 'https://www.fe-siken.com/kakomon/20_haru/q8.html'
        , 'https://www.fe-siken.com/kakomon/16_aki/q6.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q4.html'
        , 'https://www.fe-siken.com/kakomon/24_aki/q3.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q6.html'
        , 'https://www.fe-siken.com/kakomon/19_aki/q13.html'
        , 'https://www.fe-siken.com/kakomon/23_aki/q7.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q10.html'
        , 'https://www.fe-siken.com/kakomon/24_aki/q8.html'
        , 'https://www.fe-siken.com/kakomon/26_aki/q9.html'
        , 'https://www.fe-siken.com/kakomon/18_aki/q18.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q15.html'
        , 'https://www.fe-siken.com/kakomon/14_haru/q29.html'
        , 'https://www.fe-siken.com/kakomon/25_haru/q15.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q16.html'
        , 'http://www.bohyoh.com/ITEE/FIT/1996A/FIT1996AA33.html'
        , 'https://www.ap-siken.com/kakomon/22_haru/q18.html'
        , 'https://www.fe-siken.com/kakomon/28_aki/q20.html'
        , 'https://www.ap-siken.com/kakomon/22_haru/q23.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q21.html'
        , 'https://www.fe-siken.com/kakomon/30_haru/q23.html'
        , 'https://www.ap-siken.com/kakomon/23_toku/q26.html'
        , 'https://www.fe-siken.com/kakomon/27_haru/q25.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q26.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q27.html'
        , 'https://www.fe-siken.com/kakomon/28_aki/q29.html'
        , 'https://www.fe-siken.com/kakomon/25_haru/q30.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q29.html'
        , 'https://www.ap-siken.com/kakomon/30_haru/q33.html'
        , 'https://www.fe-siken.com/kakomon/23_toku/q39.html'
        , 'https://www.fe-siken.com/kakomon/24_haru/q36.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q33.html'
        , 'https://www.fe-siken.com/kakomon/31_haru/q34.html'
        , 'https://www.ap-siken.com/kakomon/29_haru/q37.html'
        , 'https://www.fe-siken.com/kakomon/26_haru/q39.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q37.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q39.html'
        , 'https://www.fe-siken.com/kakomon/27_haru/q39.html'
        , 'https://www.fe-siken.com/kakomon/02_menjo/q39.html'
        , 'https://www.fe-siken.com/kakomon/25_aki/q41.html'
        , 'https://www.fe-siken.com/kakomon/24_aki/q42.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q43.html'
        , 'https://www.fe-siken.com/kakomon/23_aki/q42.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q45.html'
        , 'https://www.ap-siken.com/kakomon/25_aki/q47.html'
        , 'https://www.fe-siken.com/kakomon/18_haru/q42.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q48.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q49.html'
        , 'https://www.ap-siken.com/kakomon/21_haru/q49.html'
        , 'https://www.fe-siken.com/kakomon/23_toku/q52.html'
        , 'https://www.ap-siken.com/kakomon/23_aki/q50.html'
        , 'https://www.fe-siken.com/kakomon/18_haru/q46.html'
        , 'https://www.fe-siken.com/kakomon/31_haru/q54.html'
        , 'https://www.fe-siken.com/kakomon/25_aki/q58.html'
        , 'https://www.ap-siken.com/kakomon/27_aki/q57.html'
        , 'https://www.fe-siken.com/kakomon/29_aki/q56.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q58.html'
        , 'https://www.sg-siken.com/kakomon/29_haru/q39.html'
        , 'https://www.fe-siken.com/kakomon/28_aki/q59.html'
        , 'https://www.fe-siken.com/kakomon/25_aki/q61.html'
        , 'https://www.fe-siken.com/kakomon/27_aki/q61.html'
        , 'https://www.fe-siken.com/kakomon/26_haru/q64.html'
        , 'https://www.fe-siken.com/kakomon/29_haru/q66.html'
        , 'https://www.fe-siken.com/kakomon/24_haru/q66.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q66.html'
        , 'https://www.fe-siken.com/kakomon/27_haru/q69.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q68.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q70.html'
        , 'https://www.fe-siken.com/kakomon/23_toku/q71.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q71.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q72.html'
        , 'https://www.fe-siken.com/kakomon/28_haru/q74.html'
        , 'https://www.fe-siken.com/kakomon/27_aki/q74.html'
        , 'https://www.fe-siken.com/kakomon/18_haru/q76.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q75.html'
        , 'https://www.fe-siken.com/kakomon/18_haru/q78.html'
        , 'https://www.fe-siken.com/kakomon/27_aki/q76.html'
        , 'https://www.fe-siken.com/kakomon/20_haru/q80.html'
        , 'https://www.fe-siken.com/kakomon/25_haru/q79.html'
    ]
    , r04m01: [
        ''
        , 'https://www.ap-siken.com/kakomon/23_aki/q1.html'
        , 'https://www.fe-siken.com/kakomon/17_haru/q7.html'
        , 'https://www.ap-siken.com/kakomon/23_toku/q3.html'
        , 'https://www.ap-siken.com/kakomon/18_aki/q31.html'
        , 'https://www.fe-siken.com/kakomon/31_haru/q4.html'
        , 'https://www.fe-siken.com/kakomon/19_aki/q56.html'
        , 'https://www.fe-siken.com/kakomon/30_haru/q6.html'
        , 'https://www.ap-siken.com/kakomon/03_moshi/q6.html'
        , 'https://www.ap-siken.com/kakomon/19_aki/q14.html'
        , 'https://www.fe-siken.com/kakomon/23_aki/q8.html'
        , 'https://www.ap-siken.com/kakomon/01_aki/q9.html'
        , 'https://www.fe-siken.com/kakomon/18_haru/q26.html'
        , 'https://www.fe-siken.com/kakomon/22_haru/q10.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q14.html'
        , 'https://www.fe-siken.com/kakomon/25_aki/q13.html'
        , 'https://www.ap-siken.com/kakomon/24_aki/q14.html'
        , 'https://www.fe-siken.com/kakomon/24_haru/q20.html'
        , 'https://www.fe-siken.com/kakomon/19_aki/q28.html'
        , 'https://www.fe-siken.com/kakomon/20_aki/q27.html'
        , 'https://www.ap-siken.com/kakomon/26_haru/q21.html'
        , 'https://www.ap-siken.com/kakomon/22_aki/q24.html'
        , 'https://www.fe-siken.com/kakomon/29_haru/q21.html'
        , 'https://www.fe-siken.com/kakomon/15_aki/q49.html'
        , 'https://www.fe-siken.com/kakomon/26_aki/q25.html'
        , 'https://www.fe-siken.com/kakomon/27_aki/q27.html'
        , 'https://www.ap-siken.com/kakomon/25_haru/q29.html'
        , 'https://www.fe-siken.com/kakomon/31_haru/q29.html'
        , 'https://www.ap-siken.com/kakomon/27_haru/q30.html'
        , 'https://www.fe-siken.com/kakomon/28_haru/q30.html'
        , 'https://www.sc-siken.com/kakomon/24_haru/am2_17.html'
        , 'https://www.fe-siken.com/kakomon/23_toku/q38.html'
        , 'https://www.fe-siken.com/kakomon/24_aki/q36.html'
        , 'https://www.fe-siken.com/kakomon/29_aki/q34.html'
        , 'https://www.fe-siken.com/kakomon/29_haru/q35.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q41.html'
        , 'https://www.fe-siken.com/kakomon/23_toku/q42.html'
        , 'https://www.ap-siken.com/kakomon/23_toku/q42.html'
        , 'https://www.ap-siken.com/kakomon/28_aki/q42.html'
        , 'https://www.fe-siken.com/kakomon/31_haru/q38.html'
        , 'https://www.fe-siken.com/kakomon/21_aki/q42.html'
        , 'https://www.fe-siken.com/kakomon/19_aki/q65.html'
        , 'https://www.fe-siken.com/kakomon/31_haru/q42.html'
        , 'https://www.ap-siken.com/kakomon/26_haru/q41.html'
        , 'https://www.fe-siken.com/kakomon/25_haru/q41.html'
        , 'https://www.ap-siken.com/kakomon/24_haru/q54.html'
        , 'https://www.fe-siken.com/kakomon/23_aki/q45.html'
        , 'https://www.ap-siken.com/kakomon/25_aki/q49.html'
        , 'https://www.ap-siken.com/kakomon/21_haru/q47.html'
        , 'https://www.fe-siken.com/kakomon/31_haru/q49.html'
        , 'https://www.ap-siken.com/kakomon/30_haru/q48.html'
        , 'https://www.ap-siken.com/kakomon/24_aki/q53.html'
        , 'https://www.sg-siken.com/kakomon/29_aki/q44.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q52.html'
        , 'https://www.fe-siken.com/kakomon/29_aki/q54.html'
        , 'https://www.ap-siken.com/kakomon/25_haru/q55.html'
        , 'https://www.ap-siken.com/kakomon/25_aki/q57.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q56.html'
        , 'https://www.fe-siken.com/kakomon/31_haru/q60.html'
        , 'https://www.ap-siken.com/kakomon/30_aki/q60.html'
        , 'https://www.sg-siken.com/kakomon/30_haru/q37.html'
        , 'https://www.ap-siken.com/kakomon/23_aki/q60.html'
        , 'https://www.fe-siken.com/kakomon/29_aki/q65.html'
        , 'https://www.ap-siken.com/kakomon/31_haru/q63.html'
        , 'https://www.ap-siken.com/kakomon/23_toku/q65.html'
        , 'https://www.ap-siken.com/kakomon/24_haru/q65.html'
        , 'https://www.ap-siken.com/kakomon/22_haru/q66.html'
        , 'https://www.ap-siken.com/kakomon/23_aki/q67.html'
        , 'https://www.ap-siken.com/kakomon/22_aki/q69.html'
        , 'https://www.ap-siken.com/kakomon/30_aki/q70.html'
        , 'https://www.fe-siken.com/kakomon/31_haru/q71.html'
        , 'https://www.ap-siken.com/kakomon/27_aki/q71.html'
        , 'https://www.fe-siken.com/kakomon/27_haru/q72.html'
        , 'https://www.fe-siken.com/kakomon/28_aki/q73.html'
        , 'https://www.ap-siken.com/kakomon/23_aki/q72.html'
        , 'https://www.fe-siken.com/kakomon/26_aki/q76.html'
        , 'https://www.ap-siken.com/kakomon/30_haru/q75.html'
        , 'https://www.fe-siken.com/kakomon/16_aki/q78.html'
        , 'https://www.fe-siken.com/kakomon/19_haru/q73.html'
        , 'https://www.sg-siken.com/kakomon/29_haru/q34.html'
        , 'https://www.ap-siken.com/kakomon/21_haru/q78.html'
    ]
    , r04m12: [
        ''
        , 'https://www.fe-siken.com/kakomon/27_haru/q2.html'
        , 'https://www.fe-siken.com/kakomon/03_menjo/q3.html'
        , 'https://www.fe-siken.com/kakomon/22_aki/q3.html'
        , 'https://www.fe-siken.com/kakomon/23_aki/q3.html'
        , 'https://www.ap-siken.com/kakomon/03_aki/q3.html'
        , 'https://www.fe-siken.com/kakomon/17_haru/q10.html'
        , 'https://www.ap-siken.com/kakomon/29_aki/q6.html'
        , 'https://www.ap-siken.com/kakomon/03_aki/q5.html'
        , 'https://www.fe-siken.com/kakomon/16_haru/q15.html'
        , 'https://www.fe-siken.com/kakomon/21_haru/q8.html'
        , 'https://www.fe-siken.com/kakomon/24_haru/q11.html'
        , 'https://www.ap-siken.com/kakomon/24_haru/q12.html'
        , 'https://www.fe-siken.com/kakomon/23_toku/q10.html'
        , 'https://www.fe-siken.com/kakomon/23_toku/q12.html'
        , 'https://www.ap-siken.com/kakomon/25_haru/q13.html'
        , 'https://www.fe-siken.com/kakomon/27_haru/q13.html'
        , 'https://www.fe-siken.com/kakomon/17_aki/q29.html'
        , 'https://www.fe-siken.com/kakomon/29_aki/q16.html'
        , 'https://www.fe-siken.com/kakomon/23_aki/q22.html'
        , 'https://www.ap-siken.com/kakomon/21_aki/q24.html'
        , 'https://www.fe-siken.com/kakomon/23_toku/q26.html'
        , 'https://www.fe-siken.com/kakomon/26_aki/q23.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q24.html'
        , 'https://www.fe-siken.com/kakomon/29_haru/q24.html'
        , 'https://www.ap-siken.com/kakomon/26_aki/q25.html'
        , 'https://www.ap-siken.com/kakomon/21_aki/q30.html'
        , 'https://www.fe-siken.com/kakomon/22_haru/q31.html'
        , 'https://www.fe-siken.com/kakomon/23_toku/q34.html'
        , 'https://www.fe-siken.com/kakomon/20_aki/q61.html'
        , 'https://www.fe-siken.com/kakomon/22_aki/q36.html'
        , 'https://www.ap-siken.com/kakomon/01_aki/q33.html'
        , 'https://www.ap-siken.com/kakomon/29_haru/q32.html'
        , 'https://www.fe-siken.com/kakomon/02_menjo/q33.html'
        , 'https://www.ap-siken.com/kakomon/03_haru/q36.html'
        , 'https://www.fe-siken.com/kakomon/29_haru/q38.html'
        , 'https://www.ap-siken.com/kakomon/31_haru/q37.html'
        , 'https://www.fe-siken.com/kakomon/26_haru/q43.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q42.html'
        , 'https://www.ap-siken.com/kakomon/03_aki/q45.html'
        , 'https://www.ap-siken.com/kakomon/26_aki/q45.html'
        , 'https://www.fe-siken.com/kakomon/27_aki/q42.html'
        , 'https://www.fe-siken.com/kakomon/02_menjo/q43.html'
        , 'https://www.fe-siken.com/kakomon/30_haru/q42.html'
        , 'https://www.fe-siken.com/kakomon/02_menjo/q44.html'
        , 'https://www.fe-siken.com/kakomon/21_haru/q46.html'
        , 'https://www.fe-siken.com/kakomon/22_aki/q46.html'
        , 'https://www.rs.kagu.tus.ac.jp/infoserv/j-siken/H12b2/am56.html'
        , 'https://www.fe-siken.com/kakomon/23_aki/q48.html'
        , 'https://www.fe-siken.com/kakomon/22_aki/q49.html'
        , 'https://www.ap-siken.com/kakomon/29_aki/q50.html'
        , 'https://www.sg-siken.com/kakomon/01_aki/q43.html'
        , 'https://www.fe-siken.com/kakomon/22_aki/q51.html'
        , 'https://www.ap-siken.com/kakomon/29_aki/q53.html'
        , 'https://www.fe-siken.com/kakomon/30_haru/q54.html'
        , 'https://www.sg-siken.com/kakomon/30_aki/q40.html'
        , 'https://www.fe-siken.com/kakomon/23_aki/q56.html'
        , 'https://www.sg-siken.com/kakomon/31_haru/q42.html'
        , 'https://www.sg-siken.com/kakomon/01_aki/q39.html'
        , 'https://www.ap-siken.com/kakomon/03_haru/q60.html'
        , 'https://www.ap-siken.com/kakomon/22_haru/q59.html'
        , 'https://www.ap-siken.com/kakomon/30_aki/q61.html'
        , 'https://www.ap-siken.com/kakomon/29_haru/q62.html'
        , 'https://www.fe-siken.com/kakomon/26_aki/q64.html'
        , 'https://www.fe-siken.com/kakomon/24_aki/q64.html'
        , 'https://www.ap-siken.com/kakomon/27_haru/q65.html'
        , 'https://www.ap-siken.com/kakomon/23_aki/q66.html'
        , 'https://www.ap-siken.com/kakomon/03_aki/q69.html'
        , 'https://www.fe-siken.com/kakomon/20_aki/q70.html'
        , 'https://www.ap-siken.com/kakomon/01_aki/q70.html'
        , 'https://www.ap-siken.com/kakomon/31_haru/q71.html'
        , 'https://www.fe-siken.com/kakomon/30_haru/q73.html'
        , 'https://www.fe-siken.com/kakomon/30_aki/q72.html'
        , 'https://www.ap-siken.com/kakomon/26_aki/q73.html'
        , 'https://www.fe-siken.com/kakomon/01_aki/q73.html'
        , 'https://www.ap-siken.com/kakomon/26_aki/q74.html'
        , 'https://www.fe-siken.com/kakomon/24_haru/q75.html'
        , 'https://www.fe-siken.com/kakomon/29_haru/q78.html'
        , 'https://www.ap-siken.com/kakomon/22_haru/q78.html'
        , 'https://www.fe-siken.com/kakomon/24_aki/q79.html'
        , 'http://itnavi.style-mods.net/question/sd18_2/sd18_2_78.htm'
    ]
}

const iframe = document.querySelector('#ifcontainer');
const selectYM = document.querySelector('#selectYM');
const selectQ = document.querySelector('#selectQ');
const prev = document.querySelector('#prev');
const next = document.querySelector('#next');

Object.keys(qs).forEach(k => {
    const option = document.createElement('option');
    option.value = k;
    option.innerText = `${k.slice(0, 3).toUpperCase()}-${k.slice(4, 6)}月`;
    selectYM.append(option);
});
applyIFrame(qs[selectYM.value][selectQ.value]);

selectYM.addEventListener('change', (e) => {
    selectQ.value = 1;
    applyIFrame(qs[selectYM.value][selectQ.value]);
});
selectQ.addEventListener('change', (e) => {
    applyIFrame(qs[selectYM.value][selectQ.value]);
});
prev.addEventListener('click', (e) => {
    if (selectQ.value <= 1) return;
    selectQ.value = Number(selectQ.value) - 1;
    applyIFrame(qs[selectYM.value][selectQ.value]);
});
next.addEventListener('click', (e) => {
    if (selectQ.value >= qs[selectYM.value].length - 1) return;
    selectQ.value = Number(selectQ.value) + 1;
    applyIFrame(qs[selectYM.value][selectQ.value]);
});

function applyIFrame(url) {
    if (iframe.src == url) return;
    iframe.src = url;
}